// app/layout.tsx
import styles from "./page.module.css";
import "./globals.css";
import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import { NotesProvider } from "@/app/context/notesContext";
import TanStackProvider from "@/components/TanStackProvider/TanStackProvider";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { Tag } from "@/types/note";
import homeStyles from "./Home.module.css";

export const metadata: Metadata = {
  title: "NoteHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal, // Додаємо пропс "modal"
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode; // Типізуємо "modal"
}>) {
  const allTags: Tag[] = ["Todo", "Work", "Personal", "Meeting", "Shopping"];

  return (
    <ClerkProvider afterSignOutUrl="/">
      <NotesProvider>
        <TanStackProvider>
          <html lang="en">
            <body
              className={`${GeistSans.variable} ${GeistMono.variable} ${styles.body}`}
            >
              <Header allTags={allTags} />
              <main className={homeStyles.main}>{children}</main>
              <div id="modal-root" /> {}
              {modal}
              <Footer />
            </body>
          </html>
        </TanStackProvider>
      </NotesProvider>
    </ClerkProvider>
  );
}
