import styles from "./page.module.css";
import "./globals.css";
import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import { NotesProvider } from "@/app/context/notesContext";
import TanStackProvider from "@/components/TanStackProvider/TanStackProvider";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";

export const metadata: Metadata = {
  title: "NoteHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider afterSignOutUrl="/">
      <NotesProvider>
        <TanStackProvider>
          <html lang="en">
            {}
            <body
              className={`${GeistSans.variable} ${GeistMono.variable} ${styles.body}`}
            >
              <Header />
              {}
              <main>{children}</main>
              <Footer />
            </body>
          </html>
        </TanStackProvider>
      </NotesProvider>
    </ClerkProvider>
  );
}
